import type { ForkOptions, UtilityProcess } from "electron";
import type { HostWorkerLaunchSpec } from "codex-collab/host-ipc";

const HOST_SERVICE_NAME = "Codex Collab Host";

export type ElectronUtilityFork = (
  modulePath: string,
  args?: string[],
  options?: ForkOptions,
) => UtilityProcess;

export interface DesktopHostWorkerLauncher {
  spawn(spec: HostWorkerLaunchSpec): Promise<void>;
}

/**
 * Electron owns utility-process lifetime while shared Host IPC owns
 * connect-first/readiness. Capabilities are generated by the native broker and
 * are never accepted by this launcher.
 */
export function createElectronHostWorkerLauncher(
  forkProcess: ElectronUtilityFork,
  workingDirectory: string,
): DesktopHostWorkerLauncher {
  const activeProcesses = new Set<UtilityProcess>();
  return {
    spawn(spec) {
      return new Promise<void>((resolve, reject) => {
        let settled = false;
        let child: UtilityProcess;
        try {
          child = forkProcess(spec.workerPath, [], {
            cwd: workingDirectory,
            env: safeWorkerEnvironment(spec.env),
            execArgv: [],
            stdio: "ignore",
            serviceName: HOST_SERVICE_NAME,
          });
        } catch (error) {
          reject(error);
          return;
        }

        activeProcesses.add(child);
        child.once("spawn", () => {
          settled = true;
          resolve();
        });
        child.once("exit", () => {
          activeProcesses.delete(child);
          if (!settled) reject(new Error("desktop_host_worker_exited_before_spawn"));
        });
        child.once("error", () => {
          if (!settled) reject(new Error("desktop_host_worker_failed_before_spawn"));
        });
      });
    },
  };
}

function safeWorkerEnvironment(source: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  const environment = { ...source };
  for (const key of Object.keys(environment)) {
    if (/^CODEX_COLLAB_HOST_.*CAPABILIT(?:Y|IES)$/i.test(key)) {
      delete environment[key];
    }
  }
  return environment;
}
